### PR TITLE
Update for core v0.13.

### PR DESCRIPTION
**Pull request by xclerc**
See https://github.com/ocaml/opam-repository/pull/15469

### CODE REVIEW

**Comment by pveber** [comment]
Thanks @xclerc, looks fine to me!

**Comment by agarwal** [comment]
Our opam file has `"core_kernel" {>= "v0.11.0"}`. Does this need to be updated now? Does this change require `core >= v0.13`?

**Comment by xclerc** [comment]
Unless I made a silly mistake, I think it is still possible
to build with `"core_kernel" {>= "v0.11.0"}`, even
with this pull request applied.

**Comment by pveber** [comment]
Is it ok to merge this PR so that I can upgrade biocaml too?

**Comment by agarwal** [comment]
Yes, please merge. Thanks.

**Comment by pveber** [comment]
@agarwal will you have time to push a new release?

**Comment by agarwal** [comment]
Yes, I can do a release. Give me about a day.

**Comment by pveber** [comment]
Thanks Ashish!

**Comment by pveber** [comment]
@agarwal gentle ping :)

**Comment by agarwal** [comment]
@pveber Release is being tracked in #23.

**Comment by pveber** [comment]
Super, thanks a lot!

Le lun. 20 janv. 2020 à 21:59, Ashish Agarwal <notifications@github.com> a
écrit :

**Pull request merged**
